runtime: python39  # Use the Python version matching your environment
entrypoint: gunicorn -b :$PORT main:app  # Adjust "app:app" if your Flask app is in a different module

env_variables:
  FLASK_ENV: 'production'
  OPENAI_API_KEY: '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'
  WHATSAPP_TOKEN: 'EAAQCw46knDUBOyONs7rMVA3YQhUU8AsPrKoEQIZBF1Hy3OtwsZAJuwgS3JJsYw4qbQFVhVVjBbtxH7ucS4C6iYUoqkmqlztvbHIFZA9Vv1SrZAPjRAMvWPNFpqsdLYReSxDTCcOtuFyteR2YotnMITt7ZCs0wA6ViV1UNbOW8hoMHJsTeP7OOASnplwy7nsRSPiATZA3XlRiy6zsR0LBwZD'  # Replace YOUR_ACCESS_TOKEN with your actual access token
  WEAVIATE_API_KEY: '37ESFfEpfIn6Csis9by0Cdq9WQl91AEP9kpY'
  WEAVIATE_URL: 'https://murrkfdqk2cac91dqye6w.c0.us-west1.gcp.weaviate.cloud'

handlers:
- url: /.*
  script: auto
